name: Build and Push Docker Images

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      build_args:
        required: false
        type: string
        default: ''
    secrets:
      DOCKER_REGISTRY:
        required: false
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        if: ${{ secrets.DOCKER_REGISTRY != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_REGISTRY != '' && format('{0}/{1}', secrets.DOCKER_REGISTRY, inputs.image_name) || inputs.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=${{ inputs.environment }}-latest
            type=raw,value=${{ inputs.environment }}-{{ github.sha }}

      - name: Parse build args
        id: build-args
        run: |
          if [ -z "${{ inputs.build_args }}" ]; then
            echo "args_json={}" >> $GITHUB_OUTPUT
          else
            # Convert build args string to JSON format
            ARGS_JSON=$(echo '${{ inputs.build_args }}' | jq -R 'split(" ") | map(split("=")) | map({(.[0]): .[1]}) | add // {}')
            echo "args_json=$ARGS_JSON" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: ${{ secrets.DOCKER_REGISTRY != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ${{ steps.build-args.outputs.args_json }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image tags
        run: |
          echo "Built image: ${{ steps.meta.outputs.tags }}"
          echo "IMAGE_TAG=${{ inputs.environment }}-{{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ inputs.environment }}-{{ github.sha }}" >> $GITHUB_OUTPUT

