name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string
      namespace:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      chart_path:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'DEPLOY_SCRIPT'
            set -e
            export KUBECONFIG=\$HOME/.kube/config || export KUBECONFIG=/etc/kubernetes/admin.conf
            
            SERVICE_NAME="${{ inputs.service }}-${{ inputs.environment }}"
            IMAGE_TAG="${{ inputs.image_tag }}"
            NAMESPACE="${{ inputs.namespace }}"
            
            echo "🚀 Deploying $SERVICE_NAME with image $IMAGE_TAG to namespace $NAMESPACE"
            
            # Check if deployment exists
            if kubectl get deployment $SERVICE_NAME -n $NAMESPACE &>/dev/null; then
              echo "📦 Updating existing deployment..."
              
              # Update image in deployment
              kubectl set image deployment/$SERVICE_NAME \
                $SERVICE_NAME=$IMAGE_TAG \
                -n $NAMESPACE || {
                  echo "⚠️  Failed to set image, trying alternative method..."
                  kubectl patch deployment $SERVICE_NAME -n $NAMESPACE -p \
                    '{"spec":{"template":{"spec":{"containers":[{"name":"'$SERVICE_NAME'","image":"'$IMAGE_TAG'"}]}}}}'
                }
              
              # Restart deployment to ensure new image is pulled
              kubectl rollout restart deployment/$SERVICE_NAME -n $NAMESPACE || true
              
              # Wait for rollout
              echo "⏳ Waiting for rollout to complete..."
              kubectl rollout status deployment/$SERVICE_NAME -n $NAMESPACE --timeout=5m || {
                echo "⚠️  Rollout status check failed, but continuing..."
                kubectl get pods -n $NAMESPACE | grep $SERVICE_NAME || true
              }
            else
              echo "📦 Deployment not found, using Helm..."
              cd /root/rensights || cd \$HOME/rensights || cd /opt/rensights
              
              if [ -d "${{ inputs.chart_path }}" ]; then
                helm upgrade --install $SERVICE_NAME \
                  ${{ inputs.chart_path }} \
                  --set image.tag=$IMAGE_TAG \
                  --set image.repository=$(echo $IMAGE_TAG | cut -d: -f1) \
                  -n $NAMESPACE \
                  --create-namespace \
                  --wait --timeout=5m || {
                    echo "⚠️  Helm deployment had issues, checking status..."
                    kubectl get pods -n $NAMESPACE | grep $SERVICE_NAME || true
                  }
              else
                echo "❌ Chart not found!"
                echo "Chart path: ${{ inputs.chart_path }}"
                exit 1
              fi
            fi
            
            echo "✅ Deployment completed for $SERVICE_NAME"
          DEPLOY_SCRIPT

      - name: Verify deployment
        run: |
          if [ -f /tmp/kubeconfig ]; then
            export KUBECONFIG=/tmp/kubeconfig
            kubectl get pods -n ${{ inputs.namespace }} | grep ${{ inputs.service }} || true
            kubectl rollout status deployment/${{ inputs.service }}-${{ inputs.environment }} \
              -n ${{ inputs.namespace }} --timeout=2m || true
          else
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
              kubectl get pods -n ${{ inputs.namespace }} | grep ${{ inputs.service }} || true
            EOF
          fi

